scripts: fix gdbus-codegen call.
gdbus-codegen would fail with the following error:
 from codegen import codegen_main
 ImportError: No module named codegen
Update PYTHONPATH environment variable so that python knows where to
find the codegen modules.